### ISSUE TITLE
Tolatás implementálása

### ISSUE THREAD

**Issue by Hirurawa** [SzFMV2021-Osz/AutomatedCar-B#10]
A tolatás működés kettő dologból rakódik össze:
- Ha a váltó R módban van, akkor az cél-irányvektor egy negatív előjelet kell kapjon. Ez implementálható a váltó szintjén, ami a vektor hosszát adja meg (-1-es szorzó megfordítja)
- Ha a váltó R módban van, akkor a kormány állása fordítva kell, hogy fordítsa az autót, hiszen egy balra tekert kormány irányvektora _"megfordítva"_ jobb irányú kanyarodást eredményez.

- [x] Hátrafelé mutató irányvektor
- [x] Fordított kanyarodás

**Comment by pintergreg** [comment]
Ez a szint, hogy a user story DoD pontjából megszületett az issue, ami viszont nincs kifejtve. Kifejtve akkor van egy issue, amikor már nem nagyon kell gondolkodni/tervezni az implementáláshoz. Ott van, hogy mivel mit kell csinálni, mi a kimenet. Én ebből nem tudnék tolatást implementálni.
