### ISSUE TITLE
Pozíció frissítése mozgásvektor alapján

### ISSUE THREAD

**Issue by Hirurawa** [SzFMV2021-Osz/AutomatedCar-B#12]
A pozíció frissítést egy új modul fogja elvégezni, amelyik az összes másik komponens után fut le, és a szükséges adatokat a VFB-tól kapja meg.

Ezek az adatok:
- A motor fordulatszámából a váltó egy _double_ típusú változót számol ki (torque). Ez, valamint az eddigi lendület adja meg a mozgásvektor hosszát. ( #8 )
- A kormány állásából (valamint ha tolatunk annak a fordítottjából), és az eddigi haladási irányból kiszámolható a fordulókör, és abból a mozgásvektor iránya ( #11 )

- [x] A mozgásvektor kiszámolása
- [x] Az autó helyzetének módosítása
> - [x]  Helyzet
> - [x]  Elfordulás

**Comment by pintergreg** [comment]
Mi határozza meg a mozgásvektort? Miből? Milyen típust jelent ez? Mi és mikor végzi el a frissítést?
