### ISSUE TITLE
Motor implementálása

### ISSUE THREAD

**Issue by Hirurawa** [SzFMV2021-Osz/AutomatedCar-B#14]
A motor a fordulatszámot tartja számon. Ha a gázpedál le van nyomva, akkor növeli, ha a fékpedál, akkor csökkenti - a lenyomás mértékétől függően. Ezentúl bevezethető egy állandó lassulás. A fordulatszám kívülről módosíthatónak kell lennie, hiszen a gearbox D üzemmódban automatikusan vált a belső fokozatok között.

- [x] Fordulatszámokról megállapodás mikor történik automata váltás
- [x] A motor a fordulatszámát számontartja
- [x] Pedálok állásától függően gyorsul/lassul
- [x] A váltó packetéből kiolvassa, hogy van-e váltás

**Comment by pintergreg** [comment]
Elegendő, ha csak a fordulatszámot számolja ki? Hogyan lesz abból sebesség, és hogyan lesz abból elmozdulásvektor? Mely osztályok felelnek ezekért, ha a Motor csak a fordulatszámot számolja?
